version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
  post_build:
    commands:
      - echo "Entered the post-build phase"
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar